[package]
name = "game5_liquidity_pool"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = { version = "0.8.4" }
soroban-token-sdk = { version = "0.8.4" }

[dev_dependencies]
soroban-sdk = { version = "0.8.4", features = ["testutils"] }